### PR TITLE
Support modifying sudoers Defaults

### PR DESCRIPTION
**Pull request by deric**
This PR introduces a possibility to modify sudoers defaults without the need to provide whole configuration file.

However, it would be only possible to add new entries:

```yaml
sudo::defaults:
  mailto: 
    value: 'root'
```
would be converted to a line in `/etc/sudoers`

```
Defaults mailto=root
```

The sudoers syntax is fairly complex:

```
     Default_Type ::= 'Defaults' |
                      'Defaults' '@' Host_List |
                      'Defaults' ':' User_List |
                      'Defaults' '!' Cmnd_List |
                      'Defaults' '>' Runas_List

     Default_Entry ::= Default_Type Parameter_List

     Parameter_List ::= Parameter |
                        Parameter ',' Parameter_List

     Parameter ::= Parameter '=' Value |
                   Parameter '+=' Value |
                   Parameter '-=' Value |
                   '!'* Parameter
```

There's a possibility to add more complex configurations:
```yaml
sudo::defaults:
  mailto:
    type: '@hosts_list'
    operator: '+='
    value: some@email.com
```

### CODE REVIEW

**Comment by bschonec** [comment]
What a great idea.  You just saved me a lot of time, too in implementing this.  I'm going to play with your changes today.

**Comment by bschonec** [comment]
@deric Would you be so kind as to slipstream my updates to your fork and resubmit this pull request?

**Comment by saz** [comment]
@deric LGTM but I'd prefer, to have separate PRs for using hiera and the defaults part. Easier to spot any issues in each part.

**Comment by deric** [comment]
@bschonec I've added your RHEL7 template modifications.
@saz I understand the PR is modifying too many files. I've added a common Ruby function that formats the defaults config. Thus each OS template requires only single line change.

**Comment by saz** [comment]
Thanks for this PR. I'll do some more changes and will get a new release published asap.

**Pull request merged**
