### PR TITLE
configure env_keep SSH_AUTH_SOCK by default in ubuntu/debian

### PR DESCRIPTION
**Pull request by ixpict**
It's very useful options, let's keep it on by default?

### CODE REVIEW

**Comment by saz** [comment]
@ixpict Have you checked, if this is a default value on Debian based systems?

**Comment by baurmatt** [comment]
I've checked Ubuntu 14.04/16.04/18.04: Its not included by default.

I would suggest to not merge this as it might lead to security problems.

A good alternative would probably be to make the "Defaults" configurable so everyone can configure sudo for their usage.

**Comment by ixpict** [comment]
It's not a default option, but very useful.

@baurmatt you mean something like presets?

**Comment by saz** [comment]
@baurmatt Same thoughts.

@ixpict I'll see if I'll have the time to come up with a better solution, but I don't think, I'll be able to get this worked out before the next release

**Comment by saz** [comment]
Please leave this PR open as a reminder for me :-)

**Comment by ixpict** [comment]
ok :)

**Comment by saz** [comment]
The `Defaults` are now configurable in master. I'll make a new release asap, but this PR isn't needed anymore.

**Pull request closed without merging**
