### PR TITLE
Add maxseq over-ride parameter

### PR DESCRIPTION
**Pull request by sudodevnull**
This Pull request is to allow for override of the default value for maxseq in the sudo conf file for RHEL7 and RHEL8

### CODE REVIEW

**Comment by sudodevnull** [comment]
@saz, hello sir! Hope you are well.
Not sure what additions are causing the failure here. I tried to mimic the use_sudoreplay parameter in order to get this change in.  Please let me know if there is anything else I need to do.
Thanks!

**Comment by saz** [comment]
@sudodevnull Can you rebase this PR and squash commits?

**Comment by saz** [comment]
If you're not interested in getting this PR merged, feel free to close it. Thanks!

**Comment by saz** [comment]
This is possible now, after #282 got merged. I'll do a new release asap

**Pull request closed without merging**
