### PR TITLE
I want to set if we include dir sudoers with augeas

### PR DESCRIPTION
**Pull request by edestecd**
I'd maybe like to do this on RedHat 6 and 7, if not replacing the main config file

### CODE REVIEW

**Comment by saz** [comment]
This needs some documentation, please.

**Comment by edestecd** [comment]
Sure, where / what would you like?  Will adding the new param to the README table suffice?

**Comment by edestecd** [comment]
@saz documented and Gemfile fixed for json_pure!

**Comment by edestecd** [comment]
Any feedback in this?  What can I do?

**Comment by davispuh** [comment]
ping? this is needed because by default `#includedir /etc/sudoers.d` is commented out so when I apply `sudo::configs` it won't be actually used since it writes it in `sudoers.d`

**Pull request merged**
