### PR TITLE
sudoversion is less os-specific, add tests

### PR DESCRIPTION
**Pull request by jyaworski**

### CODE REVIEW

**Comment by saz** [comment]
What if sudo isn't installed? This fact is used inside the module on RedHat only and will try rpm querying first.

**Comment by jyaworski** [comment]
A couple of options are available, then. In https://github.com/voxpupuli/puppet-collectd we made a minimum_version parameter to get around the 'needs two runs to configure' problem. We could look at the matrix that this module supports, and return the oldest version in the matrix. Then it would populate on first run.

Although this isn't necessarily an argument, "sudo" not being installed is very rare these days.

**Comment by jyaworski** [comment]
Another alternative is that if it returns blank or isn't installed somehow, we could then use rpm or dpkg.

**Comment by saz** [comment]
@jyaworski I like your suggestion. Querying the package manager in the fact is one way to avoid the requirement of multiple runs, as you will have a version.

@tosmi Do you know, if the warning inside sudo::conf is still required?

**Comment by jyaworski** [comment]
@saz done.

**Comment by jyaworski** [comment]
Ping @saz

**Comment by saz** [comment]
Is there a reason for closing this?

**Comment by jyaworski** [comment]
It was unmerged for some time.

**Pull request merged**
